function params = paramfields(o)
% returns struct with fields from maroi object useful for copying objects
%
% $Id$

params = struct('spm_hold', o.spm_hold,...
		'binarize', o.binarize,...
		'roithresh', o.roithresh,...
		'descrip', o.descrip,...
		'label', o.label);